# Generated by Django 2.2.8 on 2019-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_journalfee_kes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='d_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='v_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuredarticle',
            name='d_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuredarticle',
            name='v_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='artticle_cite',
            field=models.CharField(blank=True, default='N/A', max_length=200, verbose_name='Citations/Article'),
        ),
        migrations.AddField(
            model_name='journal',
            name='artticle_dl',
            field=models.CharField(blank=True, default='N/A', max_length=200, verbose_name='Downloads/Article'),
        ),
        migrations.AddField(
            model_name='journal',
            name='citation_count',
            field=models.CharField(blank=True, default='N/A', max_length=200, verbose_name='Citation Count'),
        ),
        migrations.AddField(
            model_name='journal',
            name='pub_count',
            field=models.CharField(blank=True, default='N/A', max_length=200, verbose_name='Publication Count'),
        ),
        migrations.AddField(
            model_name='journal',
            name='pub_years',
            field=models.CharField(blank=True, default='N/A', max_length=200, verbose_name='Publication Years'),
        ),
    ]
