# Generated by Django 2.2.8 on 2019-12-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20191208_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='artticle_cite',
            new_name='article_cite',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='artticle_dl',
            new_name='article_dl',
        ),
    ]
